# Generated by Django 3.2.2 on 2021-05-13 14:35

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=50, verbose_name='Image Name')),
                ('image', models.ImageField(upload_to='Article/Images/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('related_to', models.CharField(max_length=50, verbose_name='Related')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('external_links', models.URLField()),
                ('avg_read_time', models.TimeField(verbose_name='Title')),
                ('quality', models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], verbose_name='Title')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArticleCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(related_name='images', related_query_name='images', to='articles.Images', verbose_name='Images')),
                ('tags', models.ManyToManyField(related_name='tags', related_query_name='tags', to='articles.Tags', verbose_name='Tags')),
                ('updated_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArticleUpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
                'db_table': 'article',
                'ordering': ('title',),
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='article_title_1477c3_idx'),
        ),
    ]
