# Generated by Django 3.2.2 on 2021-05-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210513_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avg_read_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='external_links',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='quality',
            field=models.IntegerField(blank=True, choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], null=True, verbose_name='Quality'),
        ),
    ]
