# Generated by Django 3.2.2 on 2021-05-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210513_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='external_links',
            field=models.URLField(blank=True, null=True, verbose_name='External Links'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tags'),
        ),
    ]
