# Generated by Django 3.2.2 on 2021-05-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('articles', '0004_auto_20210513_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.RemoveField(
            model_name='article',
            name='images',
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.articlesmaster', verbose_name='Article Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title_images',
            field=models.ImageField(default=1, upload_to='Article/Images/', verbose_name='Title Images'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
