# Generated by Django 3.2.2 on 2021-05-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210513_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='avg_read_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Average read time'),
        ),
    ]
