# Generated by Django 3.2.2 on 2021-05-13 16:14

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('related_to', models.CharField(max_length=50, verbose_name='Related')),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='ArticlesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('category', models.IntegerField(blank=True, choices=[(1, 'Flutter'), (2, 'Django'), (3, 'Python'), (4, 'Dart')], null=True, verbose_name='Quality')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArticlesMasterCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('updated_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ArticlesMasterUpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ArticlesMaster',
                'verbose_name_plural': 'ArticlesMaster',
                'db_table': 'articles_master',
                'ordering': ('title',),
            },
        ),
        migrations.AddIndex(
            model_name='articlesmaster',
            index=models.Index(fields=['title'], name='articles_ma_title_11309c_idx'),
        ),
    ]
