# Generated by Django 3.2.2 on 2021-05-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesmaster',
            options={'ordering': ('category',), 'verbose_name': 'ArticlesMaster', 'verbose_name_plural': 'ArticlesMaster'},
        ),
        migrations.RemoveIndex(
            model_name='articlesmaster',
            name='articles_ma_title_11309c_idx',
        ),
        migrations.RemoveField(
            model_name='articlesmaster',
            name='title',
        ),
        migrations.AddField(
            model_name='articlesmaster',
            name='description',
            field=models.CharField(default=1, max_length=250, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlesmaster',
            name='category',
            field=models.CharField(choices=[('', 'Select'), ('Flutter', 'Flutter'), ('Django', 'Django'), ('Python', 'Python'), ('Dart', 'Dart')], default=1, max_length=25, verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='articlesmaster',
            index=models.Index(fields=['category'], name='articles_ma_categor_01e611_idx'),
        ),
    ]
