# Generated by Django 3.2.2 on 2021-05-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210513_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100, verbose_name='City Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
                'db_table': 'city_master',
                'ordering': ('city_name',),
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, verbose_name='State Name')),
                ('country_id', models.CharField(choices=[('1', 'INDIA')], default=1, max_length=1, verbose_name='Country Name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'State',
                'db_table': 'state_master',
                'ordering': ('state_name',),
            },
        ),
        migrations.AddIndex(
            model_name='statemaster',
            index=models.Index(fields=['state_name'], name='state_maste_state_n_44f927_idx'),
        ),
        migrations.AddField(
            model_name='citymaster',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.statemaster', verbose_name='State Name'),
        ),
        migrations.AddIndex(
            model_name='citymaster',
            index=models.Index(fields=['city_name'], name='city_master_city_na_d5b927_idx'),
        ),
    ]
