# Generated by Django 3.2.2 on 2021-05-14 11:55

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0003_auto_20210513_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymaster',
            options={'ordering': ('city_name',), 'verbose_name': 'City Master', 'verbose_name_plural': 'City Master'},
        ),
        migrations.AlterModelOptions(
            name='statemaster',
            options={'ordering': ('state_name',), 'verbose_name': 'State Master', 'verbose_name_plural': 'State Master'},
        ),
        migrations.AddField(
            model_name='citymaster',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CityMasterCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citymaster',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citymaster',
            name='updated_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CityMasterUpdatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citymaster',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statemaster',
            name='created_by',
            field=audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='StateMasterCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statemaster',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statemaster',
            name='updated_by',
            field=audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='StateMasterUpdatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statemaster',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
