# Generated by Django 3.2.2 on 2021-05-18 11:48

import audit_log.models.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0004_auto_20210514_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_category', models.CharField(choices=[('', 'Select'), ('Flutter', 'Flutter'), ('Django', 'Django'), ('Python', 'Python'), ('Dart', 'Dart')], max_length=25, verbose_name='Video Category')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VideoMasterCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('updated_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VideoMasterUpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
