# Generated by Django 3.2.2 on 2021-05-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_videomaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmaster',
            name='category',
            field=models.CharField(choices=[('', 'Select'), ('Dart', 'Dart'), ('Django', 'Django'), ('Flutter', 'Flutter'), ('Python', 'Python'), ('Linux', 'Linux')], max_length=25, verbose_name='Category'),
        ),
    ]
