# Generated by Django 3.2.2 on 2021-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_videos_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_playlist_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Video Play list ID'),
        ),
    ]
