# Generated by Django 3.2.2 on 2021-05-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_videos_video_playlist_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
